# Generated by Django 3.0.6 on 2020-05-15 23:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together={('user1', 'user2')},
        ),
    ]
