# Generated by Django 3.0.6 on 2020-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_setup',
            field=models.IntegerField(default=0),
        ),
    ]
