# Generated by Django 3.0.6 on 2020-05-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200512_1544'),
        ('users', '0002_users_is_setup'),
    ]

    operations = [
    ]
