# Generated by Django 3.0.6 on 2020-05-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_user'),
        ('users', '0004_merge_20200512_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='showcase_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showcase_job', to='job.Job'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_setup',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
