# Generated by Django 2.2.2 on 2020-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200512_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cropped_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
