# Generated by Django 3.0.6 on 2020-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200515_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
