# Generated by Django 3.0.6 on 2020-05-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200521_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
