# Generated by Django 3.0.6 on 2020-05-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='key_expires',
            new_name='verification_key_expiry',
        ),
    ]
