# Generated by Django 3.0.6 on 2020-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200522_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_password_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_password_key_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
