# Generated by Django 3.0.6 on 2021-03-15 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200523_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=['no-genre'], size=8),
            preserve_default=False,
        ),
    ]
