# Generated by Django 3.0.6 on 2021-03-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='genres',
            new_name='favorite_genres',
        ),
    ]
