# Generated by Django 3.0.6 on 2021-03-15 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_users_favorite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='preferred_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default='{comedy}', size=8),
            preserve_default=False,
        ),
    ]
