# Generated by Django 3.0.6 on 2021-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210315_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cropped_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
