# Generated by Django 3.0.6 on 2020-05-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upvotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upvote_post', to='posts.Posts'),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upvote_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
