# Generated by Django 3.0.6 on 2020-05-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('comment_upvotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentupvotes',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_upvote_post', to='comments.Comments'),
        ),
    ]
