# Generated by Django 3.0.6 on 2020-05-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='user1',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='user2',
            new_name='sender',
        ),
    ]
