# Generated by Django 3.0.6 on 2020-05-15 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0002_auto_20200515_2334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('sender', 'receiver')},
        ),
    ]
