# Generated by Django 3.0.6 on 2020-05-23 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200516_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
