# Generated by Django 3.0.6 on 2020-05-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200511_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
    ]
