# Generated by Django 3.0.6 on 2020-05-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_showcase'),
        ('job', '0003_remove_job_showcase'),
    ]

    operations = [
    ]
