# Generated by Django 3.0.6 on 2020-05-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_merge_20200513_0201'),
        ('job', '0007_auto_20200513_0052'),
    ]

    operations = [
    ]
